site_name: MoBI Setup Documentation
nav:
  - Home: index.md
  - About: about.md
  - Computing: computing.md
  - EEG: EEG.md
  - Wearable Eye Tracking: EyeTracking_Wearable.md
  - Tabletop Eye Tracking: EyeTracking_Tabletop.md
  - Electrophysiology: Physiology.md
  - Audio: Audio.md
  - Video: Video.md
  - Motion Capture: MotionCapture.md
  - 3D Scanning: 3D.md
  - Cogpsych: Cogpsych.md
  - Appendices: appendices.md
theme: readthedocs

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - footnotes
  - abbr
  - attr_list
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist

site_url: https://kimit0310.github.io/MoBI_Docs/